### ISSUE TITLE
agenda for the meeting 2020-03-02

### ISSUE THREAD

**Issue by mkuzak** [nlesc-sigs/software-sustainability#13]
thanks to @c-martinez for giving the points, agenda should cover:
- Reflect on the guide sprint -- how did it go & what next?
 ( - blog post?)
- Plan a course (or workshop?) on CI
- Add CI to the guide (or the Turing way)

things in brackets are my comments and suggestions

**Comment by c-martinez** [comment]
We can keep meeting notes on sharepoint. [Notes for meeting 2020-03-02](https://nlesc.sharepoint.com/:w:/s/softwaresustainability/EUk7OUbRdW1GnyYTa44EURgB9-_SWR7VUZb3bOaYD316QQ?e=ta1I46) are there.

**Comment by mkuzak** [comment]
this issue is about meeting agenda, not the minutes or notes from the meeting, those are not necessary the same. Despite this, I agree we can keep both in single document in sharepoint.
