### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by c-martinez** [nlesc-sigs/software-sustainability#6]
The Turing Way does not include a checklists -- is this something we could contribute from the guide?

**Comment by fdiblen** [comment]
The issue can be followed here:
https://github.com/alan-turing-institute/the-turing-way/issues/878

**Comment by fdiblen** [comment]
The branch is here:
https://github.com/NLeSC/the-turing-way/tree/checklist

**Comment by c-martinez** [comment]
PR https://github.com/alan-turing-institute/the-turing-way/pull/910 is still open.

**Comment by bouweandela** [comment]
The Turing way now includes checklists after every chapter, see e.g.:
https://the-turing-way.netlify.app/reproducible-research/open/open-resources.html
https://the-turing-way.netlify.app/reproducible-research/vcs/vcs-resources.html
etc

**Comment by c-martinez** [comment]
Given that there are already checklists in each chapter, PR #910 was closed. We can close this issue as well.
