### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by c-martinez** [nlesc-sigs/software-sustainability#9]
The Turing Way does not include a section on this topic -- is this something we could contribute from the guide?

**Comment by c-martinez** [comment]
`Licensing` and `Intellectual Property` sections overlap and could be merged.

**Comment by c-martinez** [comment]
@sverhoeven opened an [issue on Turing Way](https://github.com/alan-turing-institute/the-turing-way/issues/868)

**Comment by c-martinez** [comment]
Once [PR](https://github.com/alan-turing-institute/the-turing-way/pull/880) is merged, shorten software licensing chapters by pointing to the Turing Way chapters.

**Comment by mkuzak** [comment]
This PR has been merged now, I'm closing this issue.
